"""Sony MDR V2 Protocol implementation for XMDeck."""

from .arq import (
    ARQStateMachine,
    ARQTimeoutError,
    AsyncARQController,
    invert_seq,
    is_ack_required,
)
from .framing import (
    ALT_END_MARKER,
    ALT_START_MARKER,
    END_MARKER,
    ESCAPE_SENTRY,
    START_MARKER,
    Frame,
    FramingError,
    StreamParser,
    calc_checksum,
    decode_frame,
    encode_frame,
    escape_bytes,
    unescape_bytes,
)
from .messages import (
    ANCModeLiteral,
    ANCState,
    BatteryChargingStatus,
    BatteryStatus,
    CommandTable1,
    FrameDataType,
    NcAsmInquiredType,
    NcAsmMode,
    PowerInquiredType,
    SystemInquiredType,
    build_anc_query,
    build_battery_query,
    build_set_ambient_sound,
    build_set_anc_mode,
    build_set_speak_to_chat,
    build_speak_to_chat_query,
    parse_anc_state,
    parse_battery_status,
    parse_speak_to_chat,
)

__all__ = [
    # Framing
    "START_MARKER",
    "END_MARKER",
    "ESCAPE_SENTRY",
    "ALT_START_MARKER",
    "ALT_END_MARKER",
    "Frame",
    "FramingError",
    "StreamParser",
    "calc_checksum",
    "escape_bytes",
    "unescape_bytes",
    "encode_frame",
    "decode_frame",
    # Messages
    "FrameDataType",
    "CommandTable1",
    "PowerInquiredType",
    "BatteryChargingStatus",
    "NcAsmInquiredType",
    "NcAsmMode",
    "SystemInquiredType",
    "ANCModeLiteral",
    "BatteryStatus",
    "ANCState",
    "build_battery_query",
    "parse_battery_status",
    "build_anc_query",
    "parse_anc_state",
    "build_set_anc_mode",
    "build_set_ambient_sound",
    "build_speak_to_chat_query",
    "parse_speak_to_chat",
    "build_set_speak_to_chat",
    # ARQ
    "ARQStateMachine",
    "AsyncARQController",
    "ARQTimeoutError",
    "invert_seq",
    "is_ack_required",
]
